"""Definitions des questions du questionnaire et leurs poids de scoring."""

QUESTIONS = [
    {
        "id": "project_type",
        "text": "Quel type de projet veux-tu construire ?",
        "options": [
            {"label": "Application Web (SPA/MPA)", "value": "web_app"},
            {"label": "API REST / GraphQL", "value": "api"},
            {"label": "Application Mobile", "value": "mobile"},
            {"label": "Application Desktop", "value": "desktop"},
            {"label": "Outil CLI / Utilitaire systeme", "value": "cli"},
            {"label": "Data Pipeline / Machine Learning", "value": "data_ml"},
            {"label": "Systeme embarque / IoT", "value": "embedded"},
            {"label": "Jeu video", "value": "game"},
        ],
        "relevant_categories": {
            "web_app": ["language", "frontend", "backend", "database", "devops"],
            "api": ["language", "backend", "database", "devops"],
            "mobile": ["language", "mobile", "backend", "database"],
            "desktop": ["language", "desktop", "database"],
            "cli": ["language"],
            "data_ml": ["language", "database", "devops"],
            "embedded": ["language"],
            "game": ["language", "desktop"],
        },
        "weight_map": {
            "web_app": {
                "javascript": 3, "typescript": 4, "python": 2, "go": 1, "java": 2, "csharp": 2,
                "php": 2, "ruby": 2, "elixir": 2,
                "react": 3, "vue": 3, "angular": 3, "svelte": 2, "nextjs": 4,
                "express": 3, "django": 3, "flask": 1, "fastapi": 2, "spring": 2,
                "rails": 3, "laravel": 3, "gin": 1, "phoenix": 2,
                "postgresql": 3, "mysql": 2, "mongodb": 2, "redis": 2, "sqlite": 1,
                "docker": 3, "kubernetes": 2, "github_actions": 2,
            },
            "api": {
                "python": 3, "typescript": 3, "go": 4, "java": 3, "csharp": 2,
                "rust": 2, "elixir": 3, "php": 1,
                "express": 3, "django": 2, "fastapi": 4, "spring": 3,
                "gin": 4, "actix": 3, "phoenix": 3, "rails": 1, "laravel": 1, "flask": 2,
                "postgresql": 3, "mysql": 2, "mongodb": 2, "redis": 3,
                "cassandra": 2, "sqlite": 1,
                "docker": 3, "kubernetes": 3, "terraform": 2, "github_actions": 2,
            },
            "mobile": {
                "javascript": 2, "typescript": 3, "swift": 4, "kotlin": 4,
                "react_native": 3, "flutter": 3, "swiftui": 4, "jetpack_compose": 4,
                "fastapi": 2, "express": 2, "django": 1, "gin": 2, "spring": 2,
                "postgresql": 2, "mysql": 2, "mongodb": 2, "redis": 1, "sqlite": 3,
            },
            "desktop": {
                "cpp": 3, "csharp": 3, "java": 2, "rust": 3, "python": 2,
                "javascript": 2, "typescript": 2, "swift": 2,
                "electron": 3, "tauri": 3, "qt": 3, "gtk": 2,
                "sqlite": 3, "postgresql": 1,
            },
            "cli": {
                "python": 3, "go": 4, "rust": 4, "c": 3, "cpp": 2,
                "javascript": 1, "ruby": 2,
            },
            "data_ml": {
                "python": 5, "java": 2, "cpp": 1, "rust": 1,
                "go": 1,
                "postgresql": 3, "mongodb": 2, "redis": 2, "cassandra": 2,
                "docker": 3, "kubernetes": 3,
            },
            "embedded": {
                "c": 5, "cpp": 4, "rust": 4, "python": 1, "go": 1,
            },
            "game": {
                "cpp": 5, "csharp": 4, "rust": 2, "java": 1, "python": 1,
                "javascript": 1,
            },
        },
    },
    {
        "id": "performance",
        "text": "Quelle importance accordes-tu a la performance brute ?",
        "options": [
            {"label": "Peu importante - la vitesse de dev prime", "value": "low"},
            {"label": "Moderee - doit gerer une charge raisonnable", "value": "medium"},
            {"label": "Elevee - doit etre tres rapide", "value": "high"},
            {"label": "Extreme - chaque microseconde compte", "value": "extreme"},
        ],
        "weight_map": {
            "low": {
                "python": 3, "ruby": 3, "javascript": 2, "php": 2, "elixir": 1,
                "django": 3, "rails": 3, "laravel": 3, "flask": 3, "express": 2,
                "react_native": 2, "flutter": 1, "electron": 2,
            },
            "medium": {
                "go": 2, "java": 2, "csharp": 2, "kotlin": 2, "typescript": 2,
                "python": 1, "javascript": 1, "elixir": 2,
                "fastapi": 2, "spring": 2, "gin": 2, "phoenix": 2, "express": 1,
                "flutter": 2, "postgresql": 2,
            },
            "high": {
                "go": 3, "rust": 3, "cpp": 3, "java": 2, "csharp": 2, "swift": 2,
                "gin": 3, "actix": 3, "spring": 2,
                "swiftui": 2, "jetpack_compose": 2, "tauri": 2,
                "postgresql": 2, "redis": 3,
            },
            "extreme": {
                "c": 4, "cpp": 4, "rust": 4,
                "actix": 4, "gin": 2,
                "redis": 3, "cassandra": 2,
                "tauri": 2, "qt": 2,
            },
        },
    },
    {
        "id": "team_size",
        "text": "Quelle est la taille de ton equipe ?",
        "options": [
            {"label": "Solo (1 personne)", "value": "solo"},
            {"label": "Petite equipe (2-5)", "value": "small"},
            {"label": "Equipe moyenne (6-20)", "value": "medium"},
            {"label": "Grande equipe (20+)", "value": "large"},
        ],
        "weight_map": {
            "solo": {
                "python": 3, "javascript": 2, "ruby": 2, "php": 1,
                "flask": 2, "fastapi": 2, "express": 2, "rails": 2, "laravel": 2,
                "django": 2, "svelte": 2, "vue": 2,
                "react_native": 2, "flutter": 2,
                "sqlite": 3, "mongodb": 2,
                "electron": 2,
            },
            "small": {
                "typescript": 2, "python": 2, "go": 2, "kotlin": 1,
                "react": 2, "vue": 2, "nextjs": 2,
                "django": 2, "fastapi": 2, "gin": 2, "express": 2,
                "flutter": 2,
                "postgresql": 2, "mongodb": 1,
                "docker": 2, "github_actions": 2,
            },
            "medium": {
                "typescript": 3, "java": 2, "go": 2, "csharp": 2, "kotlin": 2,
                "react": 2, "angular": 2,
                "spring": 2, "django": 2, "nextjs": 2,
                "postgresql": 2,
                "docker": 2, "kubernetes": 2, "terraform": 2,
            },
            "large": {
                "typescript": 3, "java": 3, "go": 2, "csharp": 2,
                "angular": 3, "react": 2,
                "spring": 3, "django": 1,
                "postgresql": 2, "cassandra": 2,
                "kubernetes": 3, "terraform": 3, "docker": 2,
            },
        },
    },
    {
        "id": "deadline",
        "text": "Quel est ton horizon de temps ?",
        "options": [
            {"label": "Prototype rapide (quelques jours/semaines)", "value": "prototype"},
            {"label": "Projet a moyen terme (1-6 mois)", "value": "medium"},
            {"label": "Projet long terme (6+ mois)", "value": "long"},
            {"label": "Pas de contrainte de temps", "value": "none"},
        ],
        "weight_map": {
            "prototype": {
                "python": 4, "javascript": 3, "ruby": 3, "php": 2,
                "flask": 3, "express": 3, "rails": 4, "django": 3, "laravel": 3,
                "fastapi": 2, "svelte": 2, "vue": 2, "react": 2,
                "react_native": 2, "flutter": 2,
                "sqlite": 3, "mongodb": 2,
            },
            "medium": {
                "typescript": 2, "python": 2, "go": 2, "kotlin": 1,
                "react": 2, "vue": 2, "nextjs": 2,
                "django": 2, "fastapi": 2, "gin": 2, "spring": 1,
                "flutter": 2, "react_native": 1,
                "postgresql": 2, "docker": 2,
            },
            "long": {
                "typescript": 3, "java": 3, "go": 2, "rust": 2, "csharp": 2,
                "angular": 2, "react": 2, "nextjs": 2,
                "spring": 3, "django": 2, "gin": 2, "actix": 1,
                "swiftui": 2, "jetpack_compose": 2,
                "postgresql": 3, "cassandra": 2,
                "kubernetes": 2, "terraform": 2,
            },
            "none": {
                "rust": 3, "cpp": 2, "go": 2, "typescript": 1,
                "actix": 2, "gin": 1,
                "tauri": 2, "qt": 2,
            },
        },
    },
    {
        "id": "scalability",
        "text": "Quels sont tes besoins en scalabilite ?",
        "options": [
            {"label": "Un seul serveur suffit", "value": "single"},
            {"label": "Scalabilite horizontale moderee", "value": "horizontal"},
            {"label": "Haute disponibilite / tres gros trafic", "value": "massive"},
            {"label": "Pas applicable", "value": "na"},
        ],
        "weight_map": {
            "single": {
                "python": 2, "ruby": 2, "php": 2,
                "flask": 2, "rails": 2, "laravel": 2, "django": 2,
                "sqlite": 3, "postgresql": 2, "mysql": 2,
            },
            "horizontal": {
                "go": 3, "java": 2, "typescript": 2, "elixir": 2,
                "gin": 3, "spring": 2, "fastapi": 2, "phoenix": 2, "express": 2,
                "postgresql": 2, "mongodb": 2, "redis": 2,
                "docker": 3, "kubernetes": 2,
            },
            "massive": {
                "go": 3, "java": 3, "rust": 2, "elixir": 3,
                "gin": 3, "spring": 3, "actix": 2, "phoenix": 3,
                "cassandra": 4, "redis": 3, "postgresql": 2,
                "kubernetes": 4, "terraform": 3, "docker": 2,
            },
            "na": {},
        },
    },
    {
        "id": "experience",
        "text": "Quel est ton niveau d'experience en programmation ?",
        "options": [
            {"label": "Debutant (je debute)", "value": "beginner"},
            {"label": "Intermediaire (quelques projets)", "value": "intermediate"},
            {"label": "Avance (plusieurs annees)", "value": "advanced"},
            {"label": "Expert (architecte / senior)", "value": "expert"},
        ],
        "weight_map": {
            "beginner": {
                "python": 4, "javascript": 3, "ruby": 2, "php": 2,
                "flask": 2, "express": 2, "django": 2,
                "vue": 3, "svelte": 2, "react": 1,
                "flutter": 2, "react_native": 1,
                "sqlite": 3, "mongodb": 2,
                "github_actions": 2,
            },
            "intermediate": {
                "python": 2, "typescript": 2, "javascript": 2, "go": 1, "kotlin": 1,
                "react": 2, "vue": 2, "nextjs": 2,
                "django": 2, "fastapi": 2, "express": 2, "gin": 1,
                "flutter": 2, "react_native": 2,
                "postgresql": 2, "mongodb": 1, "redis": 1,
                "docker": 2,
            },
            "advanced": {
                "typescript": 2, "go": 2, "rust": 1, "java": 2, "kotlin": 2,
                "react": 2, "angular": 1, "nextjs": 2, "svelte": 1,
                "spring": 2, "gin": 2, "fastapi": 2, "phoenix": 1,
                "swiftui": 2, "jetpack_compose": 2, "tauri": 1,
                "postgresql": 2, "redis": 2, "cassandra": 1,
                "kubernetes": 2, "terraform": 2,
            },
            "expert": {
                "rust": 3, "go": 2, "cpp": 2, "elixir": 2, "java": 1,
                "actix": 2, "phoenix": 2, "spring": 2, "gin": 2,
                "angular": 2, "svelte": 1,
                "cassandra": 2, "redis": 2,
                "kubernetes": 3, "terraform": 3,
                "tauri": 2, "qt": 1,
            },
        },
    },
    {
        "id": "paradigm",
        "text": "Quel paradigme de programmation preferes-tu ?",
        "options": [
            {"label": "Oriente Objet (classes, heritage)", "value": "oop"},
            {"label": "Fonctionnel (immutabilite, fonctions pures)", "value": "functional"},
            {"label": "Multi-paradigme (flexible)", "value": "multi"},
            {"label": "Pas de preference", "value": "none"},
        ],
        "weight_map": {
            "oop": {
                "java": 3, "csharp": 3, "cpp": 2, "kotlin": 2, "swift": 2,
                "python": 2, "typescript": 1, "ruby": 2, "php": 1,
                "spring": 3, "django": 2, "angular": 2, "rails": 2, "laravel": 2,
                "jetpack_compose": 2, "swiftui": 1,
                "qt": 2,
            },
            "functional": {
                "elixir": 4, "rust": 2, "kotlin": 2, "swift": 1,
                "javascript": 1, "typescript": 1, "python": 1,
                "phoenix": 4, "react": 2, "svelte": 1,
            },
            "multi": {
                "python": 2, "typescript": 2, "kotlin": 2, "rust": 2,
                "go": 2, "swift": 1, "javascript": 1, "csharp": 1,
            },
            "none": {},
        },
    },
    {
        "id": "deployment",
        "text": "Ou vas-tu deployer ?",
        "options": [
            {"label": "Cloud (AWS, GCP, Azure)", "value": "cloud"},
            {"label": "Serveur on-premise / VPS", "value": "onprem"},
            {"label": "Serverless (Lambda, Cloud Functions)", "value": "serverless"},
            {"label": "Edge / CDN", "value": "edge"},
            {"label": "Local uniquement (pas de deploiement)", "value": "local"},
        ],
        "weight_map": {
            "cloud": {
                "docker": 4, "kubernetes": 3, "terraform": 3, "github_actions": 2,
                "go": 2, "java": 2, "python": 1, "typescript": 1,
                "spring": 2, "gin": 2, "fastapi": 1,
                "postgresql": 2, "redis": 2, "cassandra": 1,
            },
            "onprem": {
                "docker": 3, "go": 2, "java": 2, "python": 2, "php": 1,
                "django": 2, "spring": 2, "laravel": 1, "gin": 2,
                "postgresql": 3, "mysql": 2, "redis": 2,
            },
            "serverless": {
                "python": 3, "javascript": 3, "typescript": 3, "go": 2, "rust": 2,
                "fastapi": 2, "express": 2,
                "nextjs": 3,
                "github_actions": 2,
            },
            "edge": {
                "javascript": 3, "typescript": 3, "rust": 2,
                "nextjs": 3, "svelte": 2,
            },
            "local": {
                "python": 2, "sqlite": 3,
                "electron": 2, "tauri": 2,
            },
        },
    },
    {
        "id": "type_safety",
        "text": "Quelle importance accordes-tu au typage statique ?",
        "options": [
            {"label": "Pas important - je prefere la flexibilite", "value": "low"},
            {"label": "Apprecie mais pas obligatoire", "value": "medium"},
            {"label": "Important - je veux de la securite de types", "value": "high"},
            {"label": "Critique - zero tolerance aux erreurs de type", "value": "critical"},
        ],
        "weight_map": {
            "low": {
                "python": 3, "javascript": 3, "ruby": 3, "php": 2, "elixir": 1,
                "flask": 2, "express": 2, "rails": 2, "django": 2,
                "mongodb": 2, "redis": 1,
            },
            "medium": {
                "typescript": 2, "python": 1, "kotlin": 2, "go": 1,
                "fastapi": 2, "nextjs": 1,
                "vue": 1, "react": 1,
            },
            "high": {
                "typescript": 3, "java": 3, "csharp": 3, "kotlin": 3, "swift": 3,
                "go": 2, "rust": 2,
                "angular": 2, "spring": 2,
                "swiftui": 2, "jetpack_compose": 2,
                "postgresql": 2,
            },
            "critical": {
                "rust": 4, "java": 3, "csharp": 3, "typescript": 3, "swift": 3,
                "kotlin": 3, "go": 2,
                "spring": 3, "angular": 2, "actix": 2,
                "swiftui": 2, "jetpack_compose": 2,
            },
        },
    },
    {
        "id": "data_needs",
        "text": "Quels sont tes besoins en stockage de donnees ?",
        "options": [
            {"label": "Donnees relationnelles structurees (SQL)", "value": "relational"},
            {"label": "Documents / donnees flexibles (NoSQL)", "value": "document"},
            {"label": "Cache / cle-valeur a haute vitesse", "value": "kv"},
            {"label": "Mixte / je ne sais pas encore", "value": "mixed"},
            {"label": "Pas de base de donnees", "value": "none"},
        ],
        "weight_map": {
            "relational": {
                "postgresql": 4, "mysql": 3, "sqlite": 2,
                "django": 2, "spring": 2, "rails": 2, "laravel": 2,
            },
            "document": {
                "mongodb": 4, "postgresql": 1,
                "express": 1, "fastapi": 1,
            },
            "kv": {
                "redis": 4, "cassandra": 2,
                "go": 1, "rust": 1,
            },
            "mixed": {
                "postgresql": 3, "mongodb": 2, "redis": 2,
            },
            "none": {},
        },
    },
    {
        "id": "budget",
        "text": "Quel est ton budget pour les outils et services ?",
        "options": [
            {"label": "Open source uniquement (gratuit)", "value": "free"},
            {"label": "Petit budget (outils payants OK)", "value": "small"},
            {"label": "Budget entreprise", "value": "enterprise"},
        ],
        "weight_map": {
            "free": {
                "python": 2, "go": 2, "rust": 2, "javascript": 2,
                "react": 2, "vue": 2, "svelte": 2, "angular": 1,
                "django": 2, "flask": 2, "express": 2, "gin": 2, "fastapi": 2,
                "rails": 2, "phoenix": 2, "actix": 2,
                "postgresql": 3, "mysql": 2, "sqlite": 3, "mongodb": 1, "redis": 2,
                "docker": 2, "github_actions": 1,
                "electron": 2, "tauri": 2, "gtk": 2,
                "flutter": 2, "react_native": 2,
            },
            "small": {
                "typescript": 1, "kotlin": 1,
                "nextjs": 1, "github_actions": 2,
            },
            "enterprise": {
                "java": 2, "csharp": 2, "kotlin": 1,
                "spring": 3, "angular": 2,
                "kubernetes": 2, "terraform": 2,
                "cassandra": 2,
                "qt": 2,
            },
        },
    },
    {
        "id": "priority",
        "text": "Quelle est ta priorite principale ?",
        "options": [
            {"label": "Experience developpeur (DX) et simplicite", "value": "dx"},
            {"label": "Taille de la communaute et support", "value": "community"},
            {"label": "Marche de l'emploi et competences valorisees", "value": "jobs"},
            {"label": "Innovation et technologie de pointe", "value": "cutting_edge"},
            {"label": "Stabilite et maturite", "value": "stability"},
        ],
        "weight_map": {
            "dx": {
                "python": 3, "ruby": 2, "go": 2, "kotlin": 2, "swift": 1,
                "svelte": 3, "vue": 2, "fastapi": 3, "rails": 2,
                "flutter": 2, "tauri": 2,
                "sqlite": 2, "github_actions": 2,
            },
            "community": {
                "javascript": 3, "python": 3, "java": 2, "typescript": 2,
                "react": 3, "angular": 2, "vue": 2,
                "express": 2, "django": 2, "spring": 2,
                "postgresql": 2, "mysql": 2, "mongodb": 2,
                "docker": 2, "kubernetes": 2,
            },
            "jobs": {
                "javascript": 3, "typescript": 3, "python": 3, "java": 3,
                "csharp": 2, "go": 2,
                "react": 3, "angular": 2,
                "spring": 3, "django": 2, "express": 2,
                "postgresql": 2,
                "docker": 2, "kubernetes": 2,
                "react_native": 2,
            },
            "cutting_edge": {
                "rust": 3, "go": 2, "elixir": 2, "kotlin": 1, "swift": 1,
                "svelte": 3, "nextjs": 2,
                "fastapi": 2, "actix": 2, "phoenix": 2,
                "tauri": 3,
                "cassandra": 1,
                "terraform": 2,
                "flutter": 2, "jetpack_compose": 2, "swiftui": 2,
            },
            "stability": {
                "java": 3, "csharp": 2, "python": 2, "c": 2, "cpp": 2,
                "angular": 2, "react": 2,
                "spring": 3, "django": 2, "rails": 2,
                "postgresql": 3, "mysql": 2, "redis": 2,
                "docker": 2,
                "qt": 2, "electron": 2,
            },
        },
    },
]

# Synergies entre technologies - bonus quand recommandees ensemble
SYNERGIES = {
    # (tech_a, tech_b): bonus_score
    ("typescript", "react"): 3,
    ("typescript", "angular"): 3,
    ("typescript", "nextjs"): 4,
    ("typescript", "express"): 2,
    ("typescript", "vue"): 2,
    ("javascript", "react"): 2,
    ("javascript", "express"): 3,
    ("javascript", "vue"): 2,
    ("python", "django"): 3,
    ("python", "flask"): 3,
    ("python", "fastapi"): 3,
    ("go", "gin"): 4,
    ("rust", "actix"): 4,
    ("rust", "tauri"): 3,
    ("elixir", "phoenix"): 4,
    ("java", "spring"): 4,
    ("kotlin", "spring"): 3,
    ("kotlin", "jetpack_compose"): 4,
    ("swift", "swiftui"): 4,
    ("ruby", "rails"): 4,
    ("php", "laravel"): 4,
    ("csharp", "angular"): 2,
    ("react", "nextjs"): 4,
    ("react", "react_native"): 3,
    ("vue", "nextjs"): -2,  # Pas de synergie, frameworks differents
    ("nextjs", "postgresql"): 2,
    ("django", "postgresql"): 3,
    ("rails", "postgresql"): 3,
    ("spring", "postgresql"): 2,
    ("express", "mongodb"): 2,
    ("fastapi", "postgresql"): 2,
    ("docker", "kubernetes"): 3,
    ("terraform", "kubernetes"): 2,
    ("flutter", "fastapi"): 2,
    ("flutter", "gin"): 2,
    ("svelte", "fastapi"): 1,
}

# Noms lisibles des categories
CATEGORY_NAMES = {
    "language": "Langage",
    "frontend": "Frontend",
    "backend": "Backend",
    "database": "Base de donnees",
    "mobile": "Mobile",
    "desktop": "Desktop",
    "devops": "DevOps",
}
